# root_paths = ["C:/Temp", "D:/Data"]
# root_paths = ["C:/Temp", "D:/Data"]

# root_paths = ["D:/Temp"]
# root_paths = ["D:/Data/Dev/Scratch/testReact"]
# root_paths = ["D:/Data/Dev/Scratch/TestD3"]
root_paths = ["D:/", "E:/", "H:/"]
# root_paths = ["D:/Temp"]
ignore_patterns = ["**/node_modules/**", "*/$RECYCLE.BIN/*", "*/.bzvol/*"]

# root_paths = ["D:/Temp/Slate"]


# root_paths_test = ["C:/Temp", "C:/Intel"]

# root_paths_all = [
#   "D:/Ableton Gary first try Project",
#   "D:/Archive",
#   "D:/Data",
#   "D:/Music",
#   "D:/Pictures",
#   "D:/Video",
# ]

# root_paths = ["D:/Data", "D:/Pictures", "D:/Video"]
