# root_paths = ["C:/Temp", "D:/Data"]
# root_paths = ["C:/Temp", "D:/Data"]

# root_paths = ["D:/Temp"]
# root_paths = ["D:/Data/Dev/Scratch/testReact"]
# root_paths = ["D:/Data/Dev/Scratch/TestD3"]
root_paths = ["D:/", "E:/", "H:/"]
# root_paths = ["D:/Temp"]
ignore_patterns = [
  "**/node_modules/**",
  "*/$RECYCLE.BIN",
  "*/.bzvol",
  "*/System Volume Information",
  "*/Recovery",
]
