

# root_paths = ["D:/Temp", "../test-data/folder1", "../test-data/folder2"]
root_paths = ["D:/", "E:/", "H:/"]

ignore_patterns = [
  "**/node_modules/**",
  "*/$RECYCLE.BIN",
  "*/.bzvol",
  "*/System Volume Information",
  "*/Recovery",
]

spinner_key = "dots3"
