# root_paths = ["D:/Data/Dev/Scratch/testReact"]
# root_paths = ["D:/Data/Dev/Scratch/TestD3"]

# root_paths = ["C:/Temp", "../test-data/folder1", "../test-data/folder2"]
root_paths = ["../test-data/folder1", "../test-data/folder2"]

# root_paths_full_run = ["D:/", "E:/", "H:/"]
ignore_patterns = [
  "**/node_modules/**",
  "*/$RECYCLE.BIN",
  "*/.bzvol",
  "*/System Volume Information",
  "*/Recovery",
]
