'use strict';
// Design-only fictional state. Never connect this file to the product worker or user files.
const GIB = 1073741824, MIB = 1048576;
const groups = [
  {id:'video',name:'Summer film.mp4',size:1.5*GIB,copies:[{id:'va',drive:'Archive (D:)',path:'D:\\Photos\\2024\\Summer film.mp4'},{id:'vb',drive:'Backup (E:)',path:'E:\\Camera imports\\Summer film.mp4'},{id:'vc',drive:'Backup (E:)',path:'E:\\Old exports\\Summer film.mp4'}]},
  {id:'catalog',name:'Photo catalog.zip',size:512*MIB,copies:[{id:'ca',drive:'Archive (D:)',path:'D:\\Catalogs\\Photo catalog.zip'},{id:'cb',drive:'Backup (E:)',path:'E:\\Archive copies\\Photo catalog.zip'}]},
  {id:'photo',name:'Coast panorama.tif',size:48*MIB,copies:[{id:'pa',drive:'Archive (D:)',path:'D:\\Photos\\2024\\Coast panorama.tif'},{id:'pb',drive:'Backup (E:)',path:'E:\\Camera imports\\Coast panorama.tif'}]}
];
const folders = [{id:'folder',name:'2024 / Camera imports',size:1.5*GIB+48*MIB,copies:[{id:'fa',drive:'Archive (D:)',path:'D:\\Photos\\2024',files:['va','pa']},{id:'fb',drive:'Backup (E:)',path:'E:\\Camera imports',files:['vb','pb']}]}];
let state;
const $ = id => document.getElementById(id);
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const quantity = (n, word, plural=word+'s') => `${n} ${n === 1 ? word : plural}`;
const bytes = n => n >= GIB ? `${(n/GIB).toFixed(2).replace(/0$/,'')} GiB` : n ? `${(n/MIB).toFixed(0)} MiB` : '0 B';
function reset(scenario='completed') {
  state={scenario,page:scenario==='first'||scenario==='running'||scenario==='cancelled'?'scan':'results',mode:'files',group:'video',detail:false,filters:false,search:scenario==='empty'?'no-such-file':'',large:false,decisions:{va:'keep',ca:'keep',pa:'keep'},revision:0,validated:null,notice:''};
  $('scenario').value=scenario; render();
}
function physicalIds(copy) { return copy.files || [copy.id]; }
function planned() {
  const ids=new Set();
  [...groups,...folders].forEach(g=>g.copies.forEach(c=>{if(state.decisions[c.id]==='remove')physicalIds(c).forEach(id=>ids.add(id));}));
  const total=groups.reduce((sum,g)=>sum+g.copies.filter(c=>ids.has(c.id)).length*g.size,0);
  return {ids,total,count:ids.size};
}
function say(message) {$('announcement').textContent=message;}
function data() {return state.mode==='files'?groups:folders;}
function selection() {return data().find(g=>g.id===state.group)||data()[0];}
function filtered() {return data().filter(g=>(`${g.name} ${g.copies.map(c=>c.path).join(' ')}`.toLowerCase().includes(state.search.toLowerCase()))&&(!state.large||g.size>=GIB));}
function button(text,action,extra='') {return `<button data-action="${action}" ${extra}>${text}</button>`;}
function empty(title,text,action,label) {return `<div class="empty-state"><h2>${title}</h2><p>${text}</p>${action?button(label,action,'class="primary"'):''}</div>`;}
function render() {
  const first=state.scenario==='first',cancelled=state.scenario==='cancelled',p=planned();
  $('context-name').textContent=first?'New saved scan':'Photo archive';
  $('run-context').textContent=first?'Choose locations to create your first scan':cancelled?'Selected scan · Sep 8, 2026 at 11:15 AM · Cancelled':'Selected scan · Sep 8, 2026 at 9:40 AM · Completed';
  $('active-run').innerHTML=state.scenario==='running'?`<div class="active-banner"><span><strong>New scan in progress</strong> · Photo archive · Checking file contents</span>${button('View progress','progress')}</div>`:'';
  document.querySelectorAll('[data-page]').forEach(b=>{if(b.dataset.page===state.page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
  $('review-badge').textContent=p.count;
  $('footer-context').textContent=first?'No scan selected':cancelled?'Selected scan: cancelled · results unavailable':'Selected scan: Sep 8, 9:40 AM · historical results';
  $('content').dataset.page=state.page;
  $('content').innerHTML=({results:renderResults,scan:renderScan,review:renderReview,history:renderHistory})[state.page]();
}
function renderResults() {
  if(state.scenario==='first')return empty('Choose what to scan','Add folders or drives to start finding exact duplicates.','setup','Choose locations');
  if(state.scenario==='cancelled')return empty('This scan did not finish','Duplicate results are unavailable for this scan. You can start a new scan or open an earlier completed scan.','history','Choose an earlier scan');
  const list=filtered(),g=selection(),savings=list.reduce((sum,g)=>sum+(g.copies.length-1)*g.size,0),p=planned();
  return `<div class="toolbar"><div class="mode-switch" aria-label="Result type"><button data-mode="files" aria-pressed="${state.mode==='files'}">Files</button><button data-mode="folders" aria-pressed="${state.mode==='folders'}">Folders</button></div><label class="sr-only" for="search">Search paths</label><input type="search" id="search" placeholder="Search paths" value="${esc(state.search)}">${button('Search','search')}${button('Filters'+(state.large?' · 1':''),'filters',`aria-expanded="${state.filters}"`)}${button('Location preferences','rules','class="text-button"')}</div>
  ${state.filters?`<div class="filters"><label class="check"><input type="checkbox" id="large" ${state.large?'checked':''}> At least 1 GiB per copy</label><span class="muted">More filters are specified in the screen document.</span>${button('Apply filters','apply','class="primary"')}${button('Clear filters','clear')}</div>`:''}
  <div class="metrics"><div class="metric"><strong>${list.length}</strong><span>Matching sets</span></div><div class="metric"><strong>${list.reduce((s,g)=>s+g.copies.length,0)}</strong><span>Copies in these sets</span></div><div class="metric"><strong>${bytes(savings)}</strong><span>Potential savings · filtered results</span></div></div>
  ${state.notice?`<div class="warning" role="status">${esc(state.notice)}</div>`:''}
  ${!list.length?empty('No duplicates match these filters','The completed scan still has results. Clear the filters to see them.','clear','Clear filters'):`<div class="results-grid ${state.detail?'detail-open':''}"><section class="list-pane" aria-label="Duplicate sets"><div class="list-header"><span>Highest potential savings first</span><span>${quantity(list.length, 'set')}</span></div>${list.map(item=>`<button class="set-row ${item.id===g.id?'selected':''}" data-group="${item.id}" aria-pressed="${item.id===g.id}"><strong>${esc(item.name)}</strong><span class="row-meta"><span>${item.copies.length} copies · ${bytes(item.size)} each</span></span><span class="row-meta"><span>Potential savings</span><strong>${bytes((item.copies.length-1)*item.size)}</strong></span></button>`).join('')}</section><section class="comparison" aria-label="Compare copies"><div class="comparison-head">${button('Back to sets','back','class="back-to-sets"')}<h2>${esc(g.name)}</h2><p>${state.mode==='files'?'Identical content at scan time. Location can help you choose what to keep.':'Matching contents and relative structure. Root folder names may differ.'}</p></div>${g.copies.map(c=>renderCopy(g,c)).join('')}</section></div>`}
  <div class="review-strip"><div><strong>${quantity(p.count, 'distinct file')} marked · ${bytes(p.total)}</strong><p>Entire scan's review plan. Marking copies does not delete files.</p></div>${button('Review marked copies','review','class="primary"')}</div>`;
}
function renderCopy(g,c) {
  const d=state.decisions[c.id]||'undecided',changed=state.scenario==='changed'&&c.id==='vb';
  return `<article class="copy-row"><div class="copy-top"><strong>${esc(c.drive)}</strong><span class="badge ${d}">${d==='keep'?'Keep':d==='remove'?'Marked for removal':'Undecided'}</span></div><p class="copy-path">${esc(c.path)}</p><p class="copy-meta">${bytes(g.size)} · ${c.files?'2 files · includes descendants':'Modified Aug 16, 2026'}${changed?' · Changed since scan':' · Match recorded at scan time'}</p>${changed?'<p class="warning">This copy changed. Check current copies before updating the plan.</p>':''}<div class="copy-actions"><button data-decision="keep" data-copy="${c.id}" aria-label="Keep ${esc(c.path)}">Keep</button><button data-decision="remove" data-copy="${c.id}" ${changed?'disabled':''} aria-label="Mark ${esc(c.path)} for removal">Mark for removal</button><button data-decision="undecided" data-copy="${c.id}" aria-label="Reset decision for ${esc(c.path)}">Reset decision</button><button data-path="${c.id}" aria-label="View path actions for ${esc(c.path)}">Path actions</button></div></article>`;
}
function renderReview() {
  if(['first','cancelled'].includes(state.scenario))return empty('A completed scan is needed','Open a completed scan to review copies and prepare a removal plan.','history','Open history');
  const p=planned(),items=data().filter(g=>g.copies.some(c=>state.decisions[c.id]==='remove')),valid=state.validated===state.revision;
  return `<div class="page-heading"><div><h2>Review marked copies</h2><p class="muted">Photo archive · Sep 8, 9:40 AM · Plan revision ${state.revision}</p></div>${button('Return to results','results')}</div><div class="metrics"><div class="metric"><strong>${p.count}</strong><span>Distinct files marked</span></div><div class="metric"><strong>${bytes(p.total)}</strong><span>Marked for removal · whole plan</span></div></div><div class="panel"><div class="mode-switch"><button data-mode="files" aria-pressed="${state.mode==='files'}">Files</button><button data-mode="folders" aria-pressed="${state.mode==='folders'}">Folders</button></div>${items.length?items.map(g=>`<div class="review-row"><div><strong>${esc(g.name)}</strong><p>${quantity(g.copies.filter(c=>state.decisions[c.id]==='remove').length, 'copy','copies')} explicitly marked · ${g.copies.length} copies in set</p></div><button data-open-group="${g.id}">Review set</button></div>`).join(''):'<p class="muted">No explicit removals in this mode. File/folder overlaps are counted once in the total above.</p>'}<p class="note">Marking copies is reversible and does not delete files. Folder choices may cover files listed in the other mode.</p></div><div class="panel"><h3>${valid?'Demo check complete':state.validated!==null?'Plan changed — check again':'Check your removal plan'}</h3><p>${valid?'The fictional plan has a retained copy for every marked file. Real checks must come from the worker.':'Before any future removal, current copies and the latest plan need to be checked.'}</p><div class="toolbar">${button('Check marked copies','validate',`class="primary" ${!p.count?'disabled':''}`)}</div></div><div class="warning">This build can review and check a removal plan. Moving files to the Recycle Bin is not available.</div>`;
}
function renderScan() {
  if(state.scenario==='running')return `<div class="page-heading"><div><p class="eyebrow">ACTIVE SCAN · SEP 8, 11:15 AM</p><h2>Checking file contents</h2><p class="muted">Photo archive · 2 locations</p></div>${button('Cancel scan','cancel')}</div><div class="panel"><p><strong>2 hr 18 min elapsed</strong> · Example phase progress</p><div class="progress-track" role="progressbar" aria-label="Illustrative current phase progress" aria-valuenow="56" aria-valuemin="0" aria-valuemax="100"><span></span></div><div class="phase-steps"><span>Discover files</span><strong>Check content</strong><span>Compare folders</span><span>Finish</span></div><p class="note">Estimated time remaining unavailable while the read rate settles. The bar represents this illustrative phase only.</p></div><div class="panel"><h3>Current activity</h3><p>Reading duplicate candidates on Archive (D:).</p><div class="toolbar">${button('Review 3 warnings','warnings')}${button('Performance details','performance')}</div><details><summary>Scan details</summary><p>In the product: six-stage file/byte funnel, partial/full reads, cache effectiveness, known remaining work and folder substages. Rates include their measured windows.</p></details></div><p class="note">Earlier completed results remain selected in Results. This scenario is static fictional data, not live progress.</p>`;
  if(state.scenario==='cancelled')return empty('Scan cancelled','The scan stopped before duplicate analysis finished. No completed results were published. Earlier completed scans remain available.','history','Open an earlier scan');
  if(state.scenario==='first'||state.editing)return `<div class="page-heading"><h2>${state.scenario==='first'?'Choose what to scan':'Folders and drives'}</h2></div><div class="panel"><label class="form-field">Saved-scan name<input id="scan-name" value="Photo archive"></label><h3>Selected locations</h3><div class="location"><div><strong>Archive (D:)</strong><p>D:\\Photos</p></div>${button('Remove location','location-help')}</div><div class="location"><div><strong>Backup (E:)</strong><p>E:\\Camera imports</p></div>${button('Remove location','location-help')}</div><div class="toolbar">${button('+ Add folder or drive','location-help')}</div></div><div class="panel"><h3>Exclusions</h3><p>Registered cloud locations and Windows-safe ignored paths are excluded. Confirmed detection is required before starting.</p><details><summary>Advanced options</summary><label class="form-field">Repeat scans<select><option>Reuse checks for verified unchanged files</option><option>Read file content again</option></select></label><p class="muted">Ignore patterns and manual exclusions remain available here in the specified WPF design.</p></details></div><div class="toolbar">${button('Start demo scan','start','class="primary"')}<span class="muted">Concept only; no locations are accessed or saved.</span></div>`;
  return `<div class="page-heading"><h2>Scan completed</h2><span class="badge keep">Sep 8 · 9:40 AM</span></div><div class="panel"><h3>Your results are ready to review</h3><p>3 duplicate-file sets and 1 matching folder set in this fictional sample.</p><p class="muted">Potential savings and marked-removal totals are separate. File/folder matches can overlap.</p><div class="toolbar">${button('View results','results','class="primary"')}${button('Review 3 warnings','warnings')}${button('Performance details','performance')}</div></div>${button('Edit locations','setup')}`;
}
function renderHistory() {
  if(state.scenario==='first')return empty('No scans yet','Your completed, cancelled and interrupted scans will appear here.','setup','Choose locations');
  return `<div class="page-heading"><h2>Scan history</h2><p class="muted">Photo archive</p></div><div class="panel table-wrap"><table><thead><tr><th>Started</th><th>Status</th><th>Outcome</th><th>Open</th></tr></thead><tbody>${['running','cancelled'].includes(state.scenario)?`<tr><td>Sep 8, 11:15 AM</td><td>${state.scenario==='running'?'Running':'Cancelled'}</td><td>Completed results unavailable</td><td>${button('View status','progress')}</td></tr>`:''}<tr><td>Sep 8, 9:40 AM</td><td>Completed</td><td>3 exact file sets · 3 warnings</td><td>${button('Open scan','open-completed')}</td></tr></tbody></table><p class="note">Open scan changes the selected historical context. Starting or cancelling a scan is a separate action.</p></div>`;
}
function dialog(title,html){$('dialog-title').textContent=title;$('dialog-body').innerHTML=html;$('detail-dialog').showModal();$('close-dialog').focus();}
function decide(id,value) {
  const previous=state.decisions[id];state.decisions[id]=value;
  const p=planned(),kept=new Set();[...groups,...folders].forEach(g=>g.copies.forEach(c=>{if(state.decisions[c.id]==='keep')physicalIds(c).forEach(id=>kept.add(id));}));
  if([...p.ids].some(id=>kept.has(id))||groups.some(g=>g.copies.every(c=>p.ids.has(c.id)))) {state.decisions[id]=previous;state.notice='That choice conflicts with a retained copy or would leave no copy. Review the set and folder choices.';}
  else {state.revision++;state.notice='';say('Demo review decision updated. '+p.count+' distinct files marked.');}
  render();document.querySelector(`[data-decision="${value}"][data-copy="${id}"]`)?.focus();
}
function act(action) {
  const actions={results:()=>state.page='results',review:()=>state.page='review',history:()=>state.page='history',progress:()=>state.page='scan',setup:()=>{state.editing=true;state.page='scan';},saved:()=>reset(),new:()=>reset('first'),filters:()=>state.filters=!state.filters,back:()=>state.detail=false,search:()=>{state.search=$('search').value;state.group=filtered()[0]?.id||data()[0].id;},apply:()=>{state.large=$('large').checked;state.group=filtered()[0]?.id||data()[0].id;state.filters=false;},clear:()=>{state.search='';state.large=false;state.scenario=state.scenario==='empty'?'completed':state.scenario;},start:()=>reset('running'),cancel:()=>reset('cancelled'),'open-completed':()=>{if(state.scenario==='cancelled')state.scenario='completed';state.page='results';},validate:()=>{if(state.scenario==='changed'){state.notice='The demo includes a changed copy. Return to its set and check current files.';dialog('A copy needs checking','<p>The changed copy must be resolved before a real plan can be considered ready. This concept has not inspected any files.</p>');}else state.validated=state.revision;},warnings:()=>dialog(state.page==='scan'&&state.scenario==='running'?'Warnings · active scan · Sep 8, 11:15 AM':'Warnings · selected scan · Sep 8, 9:40 AM','<p><strong>3 files could not be read.</strong> Their contents were not compared.</p><p class="muted">Fictional example: permission denied in an archive folder. Actual warning categories, counts and bounded examples come from the selected run.</p>'),performance:()=>dialog('Performance details','<p>Phase durations, cache outcomes and device current/peak summaries appear here.</p><p class="muted">No measured performance is supplied by this concept. The implementation must preserve unavailable values and qualify comparisons by build, device and inputs.</p>'),rules:()=>dialog('Location preferences','<p><strong>Prefer copies in Archive (D:) over Backup (E:).</strong></p><p>The WPF workflow will let you order saved locations, preview the exact scope, then explicitly apply review decisions. Preview does not change decisions.</p><p class="note">This concept does not simulate rule application. Existing signature, revision, scope, confirmation and reversal contracts remain required.</p>'),'location-help':()=>dialog('Location selection','<p>The WPF implementation uses the existing folder picker and path validator. This concept does not open a picker, save settings or access these fictional drives.</p>')};
  actions[action]?.();if(!$('detail-dialog').open)render();
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){state.page=b.dataset.page;state.editing=false;render();$('content').focus();}else if(b.dataset.mode){state.mode=b.dataset.mode;state.group=data()[0].id;state.detail=false;render();}else if(b.dataset.group){state.group=b.dataset.group;state.detail=true;render();}else if(b.dataset.openGroup){state.group=b.dataset.openGroup;state.page='results';state.detail=true;render();}else if(b.dataset.decision)decide(b.dataset.copy,b.dataset.decision);else if(b.dataset.path){const c=[...groups,...folders].flatMap(g=>g.copies).find(c=>c.id===b.dataset.path);dialog('Path at scan time',`<p style="overflow-wrap:anywhere">${esc(c.path)}</p><p class="note">In WPF: Copy path and Show in Explorer target this exact copy. This concept performs neither operation.</p>`);}else if(b.dataset.action)act(b.dataset.action);});
$('scenario').addEventListener('change',e=>reset(e.target.value));$('reset-demo').addEventListener('click',()=>reset($('scenario').value));$('close-dialog').addEventListener('click',()=>$('detail-dialog').close());
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='search'){e.preventDefault();act('search');}if(e.ctrlKey&&e.key==='f'&&state.page==='results'){e.preventDefault();$('search')?.focus();}});
reset();
