#ifndef SUPER_DUPER_H
#define SUPER_DUPER_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result codes returned by all FFI functions.
 */
typedef enum SdResultCode {
    Ok = 0,
    InvalidHandle = 1,
    InvalidArgument = 2,
    IoError = 3,
    DatabaseError = 4,
    ScanInProgress = 5,
    ScanNotRunning = 6,
    Cancelled = 7,
    InternalError = 99,
} SdResultCode;

/**
 * Deletion execution result.
 */
typedef struct SdDeletionResult {
    uint32_t success_count;
    uint32_t error_count;
} SdDeletionResult;

/**
 * A single directory node.
 */
typedef struct SdDirectoryNode {
    int64_t id;
    char *path;
    char *name;
    int64_t parent_id;
    int64_t total_size;
    int64_t file_count;
    int64_t depth;
} SdDirectoryNode;

/**
 * A page of directory nodes.
 */
typedef struct SdDirectoryNodePage {
    struct SdDirectoryNode *nodes;
    uint32_t count;
} SdDirectoryNodePage;

/**
 * A single directory similarity pair.
 */
typedef struct SdDirectorySimilarity {
    int64_t id;
    int64_t dir_a_id;
    int64_t dir_b_id;
    char *dir_a_path;
    char *dir_b_path;
    double similarity_score;
    int64_t shared_bytes;
    char *match_type;
} SdDirectorySimilarity;

/**
 * A page of directory similarity pairs.
 */
typedef struct SdDirectorySimilarityPage {
    struct SdDirectorySimilarity *pairs;
    uint32_t count;
} SdDirectorySimilarityPage;

/**
 * A single duplicate group.
 */
typedef struct SdDuplicateGroup {
    int64_t id;
    int64_t content_hash;
    int64_t file_size;
    int64_t file_count;
    int64_t wasted_bytes;
} SdDuplicateGroup;

/**
 * A page of duplicate groups returned by paginated queries.
 */
typedef struct SdDuplicateGroupPage {
    struct SdDuplicateGroup *groups;
    uint32_t count;
    uint32_t total_available;
} SdDuplicateGroupPage;

/**
 * A single file record.
 */
typedef struct SdFileRecord {
    int64_t id;
    char *canonical_path;
    char *file_name;
    char *parent_dir;
    int64_t file_size;
    int64_t content_hash;
    uint8_t is_marked_for_deletion;
} SdFileRecord;

/**
 * A page of file records.
 */
typedef struct SdFileRecordPage {
    struct SdFileRecord *files;
    uint32_t count;
} SdFileRecordPage;

/**
 * A single scan session record.
 */
typedef struct SdSessionInfo {
    int64_t id;
    char *started_at;
    char *completed_at;
    char *status;
    char *root_paths;
    int64_t files_scanned;
    int64_t total_bytes;
    int64_t group_count;
    uint8_t is_active;
} SdSessionInfo;

/**
 * A page of scan session records.
 */
typedef struct SdSessionPage {
    struct SdSessionInfo *sessions;
    uint32_t count;
    uint32_t total_available;
} SdSessionPage;

/**
 * Progress callback signature.
 */
typedef void (*SdProgressCallback)(uint32_t phase,
                                   uint64_t current,
                                   uint64_t total,
                                   const char *message);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Auto-mark duplicate files for deletion (keeps first alphabetically).
 */
enum SdResultCode sd_auto_mark_for_deletion(uint64_t handle);

/**
 * Clear all entries from the RocksDB hash cache.
 * Does not affect the SQLite database.
 */
enum SdResultCode sd_clear_hash_cache(void);

/**
 * Clear the progress callback.
 */
enum SdResultCode sd_clear_progress_callback(uint64_t handle);

/**
 * Delete all session history and derived analysis results.
 * The scanned_file global index and hash cache are preserved.
 * Clears the engine's active_session_id.
 */
enum SdResultCode sd_delete_all_sessions(uint64_t handle);

/**
 * Delete a scan session and its duplicate groups.
 * scanned_file rows are preserved (they are the global file index).
 * If the deleted session was the active one, the active session is updated to the
 * most recent remaining completed session.
 */
enum SdResultCode sd_delete_session(uint64_t handle, int64_t session_id);

/**
 * Execute the deletion plan. Returns success/error counts via out parameters.
 *
 * When `use_trash` is non-zero, files are moved to the system Recycle Bin / Trash
 * instead of being permanently deleted.
 *
 * # Safety
 * `out_result` must be a valid pointer.
 */
enum SdResultCode sd_deletion_execute(uint64_t handle,
                                      uint8_t use_trash,
                                      struct SdDeletionResult *out_result);

/**
 * Get deletion plan summary: (file_count, total_bytes).
 *
 * # Safety
 * `out_count` and `out_bytes` must be valid pointers.
 */
enum SdResultCode sd_deletion_plan_summary(uint64_t handle, int64_t *out_count, int64_t *out_bytes);

/**
 * Create a new engine instance. Returns a handle (u64) or 0 on failure.
 *
 * # Safety
 * `db_path` must be a valid null-terminated C string.
 */
uint64_t sd_engine_create(const char *db_path);

/**
 * Destroy an engine instance and free its resources.
 */
enum SdResultCode sd_engine_destroy(uint64_t handle);

/**
 * Set ignore patterns for file scanning.
 *
 * # Safety
 * `patterns` must be a valid array of `count` null-terminated C strings.
 */
enum SdResultCode sd_engine_set_ignore_patterns(uint64_t handle,
                                                const char *const *patterns,
                                                uint32_t count);

/**
 * Set the scan paths for an engine instance.
 *
 * # Safety
 * `paths` must be a valid array of `count` null-terminated C strings.
 */
enum SdResultCode sd_engine_set_scan_paths(uint64_t handle,
                                           const char *const *paths,
                                           uint32_t count);

/**
 * Free a directory node page allocated by `sd_query_directory_children`.
 *
 * # Safety
 * `page` must have been returned by `sd_query_directory_children`.
 */
void sd_free_directory_node_page(struct SdDirectoryNodePage *page);

/**
 * Free a directory similarity page allocated by `sd_query_similar_directories`.
 *
 * # Safety
 * `page` must have been returned by `sd_query_similar_directories`.
 */
void sd_free_directory_similarity_page(struct SdDirectorySimilarityPage *page);

/**
 * Free a duplicate group page allocated by `sd_query_duplicate_groups`.
 *
 * # Safety
 * `page` must have been returned by `sd_query_duplicate_groups`.
 */
void sd_free_duplicate_group_page(struct SdDuplicateGroupPage *page);

/**
 * Free a file record page allocated by `sd_query_files_in_group`.
 *
 * # Safety
 * `page` must have been returned by `sd_query_files_in_group`.
 */
void sd_free_file_record_page(struct SdFileRecordPage *page);

/**
 * Free a session page allocated by `sd_list_sessions`.
 *
 * # Safety
 * `page` must have been returned by `sd_list_sessions`.
 */
void sd_free_session_page(struct SdSessionPage *page);

/**
 * Free a string allocated by the FFI layer.
 *
 * # Safety
 * `ptr` must have been allocated by this library (e.g., from `sd_last_error_message`).
 */
void sd_free_string(char *ptr);

/**
 * Get the last error message. Returns a C string that must be freed with `sd_free_string`.
 *
 * # Safety
 * Caller must free the returned string with `sd_free_string`.
 */
char *sd_last_error_message(void);

/**
 * List scan sessions with pagination, ordered newest-first.
 * `is_active` is set to 1 for the session matching the handle's active_session_id.
 *
 * # Safety
 * `out_page` must be a valid pointer. The returned page must be freed with `sd_free_session_page`.
 */
enum SdResultCode sd_list_sessions(uint64_t handle,
                                   int64_t offset,
                                   int64_t limit,
                                   struct SdSessionPage *out_page);

/**
 * Mark all files in a directory for deletion.
 *
 * # Safety
 * `directory_path` must be a valid null-terminated C string.
 */
enum SdResultCode sd_mark_directory_for_deletion(uint64_t handle, const char *directory_path);

/**
 * Mark a file for deletion.
 */
enum SdResultCode sd_mark_file_for_deletion(uint64_t handle, int64_t file_id);

/**
 * Query directory children. Pass parent_id = -1 for root directories.
 *
 * # Safety
 * `out_page` must be a valid pointer. The returned page must be freed with `sd_free_directory_node_page`.
 */
enum SdResultCode sd_query_directory_children(uint64_t handle,
                                              int64_t parent_id,
                                              int64_t offset,
                                              int64_t limit,
                                              struct SdDirectoryNodePage *out_page);

/**
 * Query duplicate groups with pagination.
 *
 * # Safety
 * `out_page` must be a valid pointer. The returned page must be freed with `sd_free_duplicate_group_page`.
 */
enum SdResultCode sd_query_duplicate_groups(uint64_t handle,
                                            int64_t offset,
                                            int64_t limit,
                                            struct SdDuplicateGroupPage *out_page);

/**
 * Query files in a duplicate group.
 *
 * # Safety
 * `out_page` must be a valid pointer. The returned page must be freed with `sd_free_file_record_page`.
 */
enum SdResultCode sd_query_files_in_group(uint64_t handle,
                                          int64_t group_id,
                                          struct SdFileRecordPage *out_page);

/**
 * Query similar directory pairs above a minimum score.
 *
 * # Safety
 * `out_page` must be a valid pointer. The returned page must be freed with `sd_free_directory_similarity_page`.
 */
enum SdResultCode sd_query_similar_directories(uint64_t handle,
                                               double min_score,
                                               int64_t offset,
                                               int64_t limit,
                                               struct SdDirectorySimilarityPage *out_page);

/**
 * Request cancellation of the current scan.
 */
enum SdResultCode sd_scan_cancel(uint64_t handle);

/**
 * Check if a scan is currently running.
 */
bool sd_scan_is_running(uint64_t handle);

/**
 * Start a synchronous scan. Blocks until complete.
 */
enum SdResultCode sd_scan_start(uint64_t handle);

/**
 * Set the active session used by all query functions.
 */
enum SdResultCode sd_set_active_session(uint64_t handle, int64_t session_id);

/**
 * Set a progress callback for scan operations.
 */
enum SdResultCode sd_set_progress_callback(uint64_t handle, SdProgressCallback callback);

/**
 * Truncate all SQLite tables (sessions, files, groups, directory data, deletion plan).
 * The hash cache (RocksDB) is NOT touched.
 * Clears the engine's active_session_id.
 */
enum SdResultCode sd_truncate_database(uint64_t handle);

/**
 * Unmark a file from the deletion plan.
 */
enum SdResultCode sd_unmark_file_for_deletion(uint64_t handle, int64_t file_id);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* SUPER_DUPER_H */
